try fix deploy

diff --git a/.github/workflows/cdkactions_build-and-deploy.yaml b/.github/workflows/cdkactions_build-and-deploy.yaml
--- a/.github/workflows/cdkactions_build-and-deploy.yaml
+++ b/.github/workflows/cdkactions_build-and-deploy.yaml
@@ -210,6 +210,9 @@ jobs:
       - uses: actions/checkout@v2
       - name: Deploy
         run: |-
+          # default options to make sure failures stop script execution
+          set -euo pipefail
+
           curl -s -X GET -H "Content-Type: application/json" -H "Authorization: Bearer $DO_AUTH_TOKEN" "https://api.digitalocean.com/v2/kubernetes/clusters/${K8S_CLUSTER_ID}/kubeconfig" > /kubeconfig.conf
 
           export KUBECONFIG=/kubeconfig.conf
@@ -225,12 +228,19 @@ jobs:
           fi
 
           helm repo add pennlabs https://helm.pennlabs.org/
-
           for i in {1..10}; do
-            helm upgrade --install --atomic --set=image_tag=$IMAGE_TAG -f k8s/values.yaml --version "${DEPLOY_TAG}" $RELEASE_NAME pennlabs/icarus && exit 0
+            # This is bash soup, but it'll do.
+            # 1. Attempt to install with helm
+            # 2. If this succeeds, exit with a success status code
+            # 3. If it fails, mark the command as succeeded so that '-e' doesn't kick us out
+            # 4. Wait 10s and try again
+            helm upgrade --install --atomic --set=image_tag=$IMAGE_TAG -f k8s/values.yaml --version "${DEPLOY_TAG}" $RELEASE_NAME pennlabs/icarus && exit 0 || true
             sleep 10s
             echo "Retrying deploy for $i times"
           done
+
+          # If we get here, all helm installs failed so our command should fail
+          exit 1
         env:
           IMAGE_TAG: ${{ github.sha }}
           DO_AUTH_TOKEN: ${{ secrets.DO_AUTH_TOKEN }}
